### ISSUE TITLE
Erro em alterar ou cadastrar cliente Magento 2.4

### ISSUE THREAD

**Issue by SergioMordente** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#70]
Apache 2.4
php 7.4.6
Atualizei de 2.3.5-p1 para 2.4.2 e estou tendo erro, alguém passou por isso?
 
TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /home/photocolor/public_html/vendor/magento/module-customer/Block/Widget/Dob.php:425 Stack trace: #0 /home/photocolor/public_html/vendor/magento/module-customer/Block/Widget/Dob.php(425): iterator_to_array(NULL) #1 /home/photocolor/public_html/vendor/magento/module-customer/view/frontend/templates/widget/dob.phtml(27): Magento\Customer\Block\Widget\Dob->getTranslatedCalendarConfigJson() #2 /home/photocolor/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/photocolo...') #3 /home/photocolor/public_html/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Customer\Block\Widget\Dob), '/home/photocolo...', Array) #4 /home/photocolor/public_html/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/home/photocolo...') #5 ...

**Comment by corpsysgit** [comment]
Estou tendo o mesmo problema. 

PHP 7.4
Magento 2.4.2-p1

**Comment by igorfigueiredogen** [comment]
Bom dia.

Parece que o problema acontece por causa do date-picker no idioma português.
Issue:
https://github.com/magento/magento2/issues/33280

Parece que o problema só acontece a partir da versão 2.4.1.

O que me parece ser uma possibilidade é sobrescrever o template abaixo e cometar a chamada da função getTranslatedCalendarConfigJson e a chamada do javascript.

Template:
module-customer/view/frontend/templates/widget/dob.phtml

**Comment by RoninX2** [comment]
Também estava com esse problema, ele acontece por causa do formato do calendário. 

Nesse caso vá até lojas -> configurações ->clientes e desative a opçãao de data de aniversário do cadastro de clientes.
